/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0 and the Server Side Public License, v 1; you may not use this file except
 * in compliance with, at your election, the Elastic License 2.0 or the Server
 * Side Public License, v 1.
 */

import static org.elasticsearch.gradle.PropertyNormalization.IGNORE_VALUE
import org.elasticsearch.gradle.internal.info.BuildParams

apply plugin: 'elasticsearch.standalone-rest-test'
apply plugin: 'elasticsearch.rest-test'
apply plugin: 'elasticsearch.rest-resources'
apply plugin: 'elasticsearch.s3-integ-test'

final Project repositoryPlugin = project(':plugins:repository-s3')

dependencies {
  testImplementation testArtifact(project(':qa:snapshot-based-recoveries'))
  testImplementation repositoryPlugin
}

restResources {
  restApi {
    include 'indices', 'search', 'bulk', 'snapshot'
  }
}

s3Fixture.configure 's3-snapshot-based-recoveries', 'snapshot_based_recoveries', 'integTest'

testClusters.matching { it.name == "integTest" }.configureEach {
  testDistribution = 'DEFAULT'
  numberOfNodes = 3

  setting 'xpack.security.enabled', 'false'
}

tasks.register("s3ThirdPartyTest") {
  dependsOn "integTest"
}
